#.gitlab-ci.yml

stages:
    - python

python:
    image: python:3.7
    stage: python
    script:
        - pwd
        - python --version
        # - pip3 install --upgrade tensorflow
        - pip3 install pandas
        - pip3 install numpy
        - pip3 install sklearn
        - pip3 install pickle-mixin
        - pip3 install requests
        - pip3 install jsonlib
        # - pip3 install keras
        # - pip3 install pillow
        - python3 ./ML_Projects/flask/Iris/iris_model.py

